default:
	
schematics:	schematics.tex
	pdflatex schematics.tex
	pdftoppm schematics.pdf|pnmtopng > schematics.png
	rm schematics.pdf
cleanup:
	rm *.xml *.bbl *.gz *.log *.aux *.blg *.aux *.bcf *.toc *.nav *.out
	
